
class ReturnTypes_ {
	static DEFAULT = "DEFAULT";

	static ERROR = "ERROR";

	static GET_ASSETS_COUNT = "GET_ASSETS_COUNT";

	static CREATE_ASSET = "CREATE_ASSET";

	static GET_NEED_FILES_AND_FOLDERS_TO_DOWNLOAD = "GET_NEED_FILES_AND_FOLDERS_TO_DOWNLOAD";

	static GET_ASSETS = "GET_ASSETS";

	static TOKEN_RESELLER = "TOKEN_RESELLER";

	static GET_INFO_RESELLER_FROM_TOKEN = "GET_INFO_RESELLER_FROM_TOKEN";

	static GET_KEYS_FOR_RESELLER = "GET_KEYS_FOR_RESELLER";

	static GET_COUNT_KEYS_OF_RESELLER = "GET_COUNT_KEYS_OF_RESELLER";

	static GEN_KEY = "GEN_KEY";

	static DOWNLOAD_FILE_WITH_USER_TOKEN = "DOWNLOAD_FILE_WITH_USER_TOKEN";

	static ONLINE = "ONLINE";

	static TOTAL = "TOTAL";

	static GET_MAIL = "GET_MAIL";

	static TOKEN_USER = "TOKEN_USER";

	static LOAD_PROFILE_IMAGE = "LOAD_PROFILE_IMAGE";

	static VERIFY_EMAIL = "VERIFY_EMAIL";

	static REGISTER_USER = "REGISTER_USER";

	static GET_INFO_FROM_TOKEN = "GET_INFO_FROM_TOKEN";

	static ACTIVATE_KEY = "ACTIVATE_KEY";
} 

type ReturnTypes = 'DEFAULT'
				 | 'ERROR'
				 | 'GET_ASSETS_COUNT'
				 | 'CREATE_ASSET'
				 | 'GET_NEED_FILES_AND_FOLDERS_TO_DOWNLOAD'
				 | 'GET_ASSETS'
				 | 'TOKEN_RESELLER'
				 | 'GET_INFO_RESELLER_FROM_TOKEN'
				 | 'GET_KEYS_FOR_RESELLER'
				 | 'GET_COUNT_KEYS_OF_RESELLER'
				 | 'GEN_KEY'
				 | 'DOWNLOAD_FILE_WITH_USER_TOKEN'
				 | 'ONLINE'
				 | 'TOTAL'
				 | 'GET_MAIL'
				 | 'TOKEN_USER'
				 | 'LOAD_PROFILE_IMAGE'
				 | 'VERIFY_EMAIL'
				 | 'REGISTER_USER'
				 | 'GET_INFO_FROM_TOKEN'
				 | 'ACTIVATE_KEY'
				 | "GET_CHANGE_LOGS_COUNT"
				 | "GET_CHANGE_LOGS"
				 | 'GET_CURRENT_VERSION_INJECTOR'
				 | 'EDIT_ASSET'
				 | 'GET_ASSET_BY_ID'
				 | 'DELETE_ASSET'
				 | 'GET_USER_PROFILE_IMAGE'
				 | 'INC_VIEW_COUNT_OF_ASSET'
				 | 'INC_INSTALL_COUNT_OF_ASSET'
				 | 'INSTALL_ASSET';





export interface TypeResult {
	type : string
}

export default ReturnTypes
